### ISSUE TITLE
OMOP MEASUREMENT Table Mapping

### ISSUE THREAD

**Issue by LukeBenson21** [spe-uob/HealthcareLakeETL#9]
Using the Parquet/CSV file, create a notebook that maps the data from the file into the OMOP data model for the MEASUREMENT table.
Setting up the notebook with AWS https://docs.aws.amazon.com/glue/latest/dg/dev-endpoint-tutorial-local-jupyter.html

**Comment by jagosherred** [comment]
Had some issues with split blood pressure values but think all done now - want to discuss at next meeting
